### PR TITLE
Add toggle setting for NIP-04 DMs

### PR DESCRIPTION
**Pull request by aaccioly**

### CODE REVIEW

**Comment by barrydeen** [comment]
We will not allow nip04 period, have to reject this one

We have to be opinionated especially when it comes to garbage like nip04

**Comment by aaccioly** [comment]
No worries, while I agree with you, I'll keep it on my fork as unfortunately some of my contacts aren't using NIP-17 enabled clients.

**Comment by barrydeen** [comment]
> No worries, while I agree with you, I'll keep it on my fork as unfortunately some of my contacts aren't using NIP-17 enabled clients.

I bet you those clients also don't actually use your chat relay preferences either! So probably won't affect anything

**Comment by aaccioly** [comment]
You are correct to an extent. Most of the clients in question still ignore Kind 10050, so the change to the chat relay is somewhat redundant (to be fair, disallowing the DM kind there was also redundant for the same reason—i.e., clients that didn’t implement NIP-17 won’t find the chat relay anyway). NIP-65, on the other hand, is supported by plenty of clients that don’t yet support NIP-17, e.g., Nostrudel, meaning that kind 4 events are sent to the inbox relay.

Just to be clear, I’m not trying to convince you to reopen this PR. Having NIP-04 off by default is a good decision (and even with this PR, it’s still off by default but with a toggle). I hope to remove this toggle from my fork soon, I just need a few key clients to implement NIP-17.

**Pull request closed without merging**
